return { }

-- return {
--   {
--     "yetone/avante.nvim",
--     event = "VeryLazy",
--     opts = {
--       provider = "ollama",
--       providers = {
--         ollama = {
--           endpoint = "http://localhost:11434",
--           -- pick your pulled model:
--           model = "deepseek-coder-v2:16b",
--           num_ctx = 8192,       -- context window to taste
--           temperature = 0.2,
--         },
--       },
--     },
--     dependencies = {
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     --- The below dependencies are optional,
--     "echasnovski/mini.pick", -- for file_selector provider mini.pick
--     "nvim-telescope/telescope.nvim", -- for file_selector provider telescope
--     "hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
--     "ibhagwan/fzf-lua", -- for file_selector provider fzf
--     "stevearc/dressing.nvim", -- for input provider dressing
--     "folke/snacks.nvim", -- for input provider snacks
--     "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
--     }
--   }
-- }
